//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrograAvanzada.Northwind.Products.Model
{
     using System.Runtime.Serialization;using System;
    using System.Collections.Generic;
    [DataContract] public partial class Products
    {
        [DataMember] public int ProductID { get; set; }
        [DataMember] public string ProductName { get; set; }
        [DataMember] public Nullable<int> SupplierID { get; set; }
        [DataMember] public Nullable<int> CategoryID { get; set; }
        [DataMember] public string QuantityPerUnit { get; set; }
        [DataMember] public Nullable<decimal> UnitPrice { get; set; }
        [DataMember] public Nullable<short> UnitsInStock { get; set; }
        [DataMember] public Nullable<short> UnitsOnOrder { get; set; }
        [DataMember] public Nullable<short> ReorderLevel { get; set; }
        [DataMember] public bool Discontinued { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Suppliers Suppliers { get; set; }
    }
}
