//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrograAvanzada.Northwind.Products.Model
{
     using System.Runtime.Serialization;using System;
    using System.Collections.Generic;
    [DataContract] public partial class Suppliers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Suppliers()
        {
            this.Products = new HashSet<Products>();
        }
    
        [DataMember] public int SupplierID { get; set; }
        [DataMember] public string CompanyName { get; set; }
        [DataMember] public string ContactName { get; set; }
        [DataMember] public string ContactTitle { get; set; }
        [DataMember] public string Address { get; set; }
        [DataMember] public string City { get; set; }
        [DataMember] public string Region { get; set; }
        [DataMember] public string PostalCode { get; set; }
        [DataMember] public string Country { get; set; }
        [DataMember] public string Phone { get; set; }
        [DataMember] public string Fax { get; set; }
        [DataMember] public string HomePage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Products> Products { get; set; }
    }
}
